# Docker Compose pour MediScribe
# Permet de déployer facilement l'application en production

version: '3.8'

services:
  # Application principale
  mediscribe-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediscribe-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      # Variables d'environnement de production
      NODE_ENV: production
      PORT: 3001
      
      # À configurer via fichier .env ou secrets Docker
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      VITE_ENCRYPTION_KEY: ${VITE_ENCRYPTION_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
      
      # Optionnel - Monitoring
      SENTRY_DSN: ${SENTRY_DSN:-}
      
    volumes:
      # Logs persistants
      - ./logs:/app/logs
      
    networks:
      - mediscribe-network
      
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Limites de ressources
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  mediscribe-network:
    driver: bridge

volumes:
  logs:
    driver: local
